version: '3.8'

services:
  # ---------------------------
  # Qdrant: Vector Store
  # ---------------------------
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"    # HTTP API & UI
      - "6334:6334"    # gRPC
    volumes:
      - ./qdrant_data:/qdrant/storage   # persistent storage
    restart: unless-stopped

  # ---------------------------
  # Neo4j: Graph Database
  # ---------------------------
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"    # Browser UI
      - "7687:7687"    # Bolt (driver) protocol
    environment:
      NEO4J_AUTH: "neo4j/password"      # username/password
    volumes:
      - ./neo4j_data:/data             # persistent storage
    restart: unless-stopped
